name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: <registry url>
    - name: Install dependencies
      run: yarn install
    - name: ESLint
      run: yarn lint-js
    - name: TypeScript
      run: yarn lint-ts
    - name: Unit tests
      run: yarn test
